import type { Metadata } from "next";
import localFont from "next/font/local";
import { SocketProvider } from "./context/SocketProvider";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SocketProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} flex flex-col items-center justify-center w-[100vw] h-[100vh]`}
        >
          <Navbar />
          {children}
        </body>
      </SocketProvider>
    </html>
  );
}
